Yamato-Security/takajo

src/takajo.nim, src/takajopkg/submodule.nim, takajo.nimble, tests/testsubmodule.nim
=> replace docopt to cli-gen

README-Japanese.md, README.md, src/takajo.nim
=> customize help

src/takajo.nim, src/takajopkg/sysmonProcessTree.nim
- added process tree output
I would appreciate it if you could review when you have time.
=> added process tree output

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajo.nim, src/takajopkg/vtDomainLookup.nim, src/takajopkg/vtHashLookup.nim, src/takajopkg/vtIpLookup.nim, takajo.nimble
- Related  #30
- Changed `httpclient` library to `Puppy`
-  to reduce extra DLLs for windows
I would appreciate it if you could review when you have time🙏
=> chg: Replace httpclient with Puppy

src/takajopkg/timelineSuspiciousProcesses.nim
I found a minor typo and fixed it :)
I would appreciate it if you could review when you have time🙏
=> fix typo in timeline-suspicious-processes

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajo.nim
@fukusuket Could you check this and translate the rest of the Japanese for me? There is just a little left.
=> finalize 2.1.0

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/extractScriptblocks.nim
- fixed: #71
- OS: Windows11
- Hayabusa v2.10.1
- Nim: 2.0.0
I performed the steps to reproduce https://github.com/Yamato-Security/takajo/issues/71#issue-2006288033 and confirmed that extracted text with line breaks was output as shown below. 
```
Function Get-Win32Constants
{
$Win32Constants = New-Object System.Object
$Win32Constants | Add-Member -MemberType NoteProperty -Name MEM_COMMIT -Value 0x00001000
$Win32Constants | Add-Member -MemberType NoteProperty -Name MEM_RESERVE -Value 0x00002000
$Win32Constants | Add-Member -MemberType NoteProperty -Name PAGE_NOACCESS -Value 0x01
$Win32Constants | Add-Member -MemberType NoteProperty -Name PAGE_READONLY -Value 0x02
$Win32Constants | Add-Member -MemberType NoteProperty -Name PAGE_READWRITE -Value 0x04
$Win32Constants | Add-Member -MemberType …
```
=> fix: add newline(`\n`) handling `extract-scriptblocks` command extracted script text 

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajo.nim, src/takajopkg/extractTTPs.nim, src/takajopkg/ttpVisualize.nim, takajo.nimble
- feat: #76
- added `extract-ttps` command
- creates JSON in a format that can be imported into MITRE ATT&CK Navigator
example:
```json
{
"name": "Hayabusa detection result heatmap",
"versions": {
"attack": "14",
"navigator": "4.9.1",
"layer": "4.5"
},
"domain": "enterprise-attack",
"description": "Hayabusa detection result heatmap",
"techniques": [
{
"color": "#fd8d3c",
"techniqueID": "T1070.006"
},
{
"color": "#fd8d3c",
"techniqueID": "T1098"
}
]
}
```
- Hayabusa v2.12.0-dev
- Nim: 2.0.0
```
% ./takajo extract-ttps -t out.jsonl -q
Started the Extract TTPs command.
This command extracts TTPs and creates JSON in a format that can be imported into MITRE ATT&CK Navigator.
Total lines: 32287
100%|█████████████████████████| …
```
=> feat: add `extract-ttps` command

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/timelineSuspiciousProcesses.nim, takajo.nimble
Closes https://github.com/Yamato-Security/takajo/issues/86
I decided to finalize it for a new release.
=> Fixed CSV output bug and finalized for 2.3.1

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/general.nim, src/takajopkg/ttpVisualizeSigma.nim, takajo.nimble
=> feat: add `ttp-visualize-sigma` command

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackProcesses.nim
=> feat: add `stack-processes` command

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackCmdlines.nim
- Closed: #94 
- Nim: 2.0.2
The stack command has almost duplicate code, so we plan to refactor it all together in #99 ...
=> feat: add `stack-cmdlines`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackDNS.nim
=> feat: add `stack-dns`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackTasks.nim
=> feat: add `stack-tasks` command

src/takajo.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackServices.nim
=> feat: add `stack-services`

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackTasks.nim, src/takajopkg/timelineTasks.nim
=> feat: add `timeline-tasks` command

CHANGELOG-Japanese.md, CHANGELOG.md
Sorry, I forgot to update the title in the changelog
=> fix 2.4.0 changelog

src/takajo.nim, src/takajopkg/extractScriptblocks.nim, src/takajopkg/general.nim, src/takajopkg/listDomains.nim, src/takajopkg/listHashes.nim, src/takajopkg/listIpAddresses.nim, src/takajopkg/splitCsvTimeline.nim, src/takajopkg/splitJsonTimeline.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackDNS.nim, src/takajopkg/stackLogons.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackServices.nim, src/takajopkg/stackTasks.nim, src/takajopkg/stackUtil.nim, src/takajopkg/sysmonProcessTree.nim, src/takajopkg/timelineLogon.nim, src/takajopkg/timelinePartitionDiagnostic.nim, src/takajopkg/timelineSuspiciousProcesses.nim, src/takajopkg/timelineTasks.nim, src/takajopkg/ttpResult.nim, src/takajopkg/ttpSummary.nim, src/takajopkg/ttpVisualize.nim, src/takajopkg/ttpVisualizeSigma.nim, src/takajopkg/vtDomainLookup.nim, src/takajopkg/vtHashLookup.nim, src/takajopkg/vtIpLookup.nim, src/takajopkg/vtResult.nim
- Related: #99
- Refactor duplicated following codes
- output ElapstedTime
- output TTP result
- output VirusTotal result 
In the integration test below, I confirmed that the all commands succeeded.
https://github.com/Yamato-Security/takajo/actions/runs/8027721497
=> refactor: remove duplicated codes

README-Japanese.md, README.md
=> added BSidesTokyo badge

CHANGELOG-Japanese.md, CHANGELOG.md, README.md, src/takajo.nim, src/takajopkg/automagic.nim, src/takajopkg/extractScriptblocks.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackProcesses.nim, takajo.nimble
Sorry I didn't have time to update the Japanese readme as there was a lot to update. (Still need to fix some things..) but since we don't have time I think we should release as is and then update the Japanese readme after that. What do you think?
=> finalize 2.5.0

.github/workflows/integration-test.yml, src/takajopkg/stackTasks.nim
- Closed: #148 
- Hayabusa v2.15.1-dev
- Nim: 2.0.2
```
% ./takajo stack-tasks -t timeline.jsonl -q --ignoreSecurity
Started the stack-tasks command
This command will stack new scheduled tasks from Security 4698 events
File: timeline.jsonl (32.45 MB)
Total lines: 32,513
Scanning the Hayabusa timeline. Please wait.
100%|█████████████████████████| 32513/32513 [ 0.4s< 0.0s, 115.02k/sec]
No stack-tasks results where found.
Elapsed time: 0 hours, 0 minutes, 0 seconds
fukusuke@fukusukenoMacBook-Air hayabusa-2.13.0-mac % ./takajo stack-tasks -t timeline.jsonl -q
Started the stack-tasks command
This command will stack new scheduled tasks from Security 4698 events
File: …
```
=> 148 fix ignored options

CHANGELOG-Japanese.md, CHANGELOG.md, config.nims
Fixes https://github.com/Yamato-Security/takajo/issues/158
=> add-no-incompatible-function-pointer-types-option

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajopkg/htmlReport.nim
Fixed: #169 
I added an error message and made the program terminate at that point.
=> fix #169 json line errors

src/takajopkg/htmlReport.nim, templates/index.template
=> #174 fix Consolidate Rules table

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/htmlReport.nim, templates/computer_summary.template, templates/content.template
=> fix #179 Create a Computer Summary page

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/htmlReport.nim, takajo.nimble, templates/index.template
#175 
@YamatoSecurity 
I've implemented it, please check back when you have time.
=> add detection rule list

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/htmlReport.nim
#176 fix and A bug in which graphs were being aggregated to the First Date for each rule has been fixed.
Closes https://github.com/Yamato-Security/takajo/issues/191
=> fix #176 and graph bug fix

src/takajopkg/htmlReport.nim
Fixed “Dates with most total detections” was showing the oldest date detected.
=> fix #194 Fix “Dates with most total detection”

src/takajo.nim, src/takajopkg/htmlReport.nim, src/takajopkg/web/controllers/computers.nim, src/takajopkg/web/controllers/controller.nim, src/takajopkg/web/controllers/summary.nim, src/takajopkg/web/static/computer_summary.htm, src/takajopkg/web/static/content.htm, src/takajopkg/web/static/index.htm, src/takajopkg/web/urls.nim
Allows filtering by rules. But you need click search button.
=> fix #177 Allow filtering on the Chart by Rules

.github/workflows/release.yml
- Closed #203 
https://github.com/Yamato-Security/takajo/actions/runs/11492121348
=> fix: release automation action's packages name

README-Japanese.md, README.md
The description of the ttp-visualize-sigma command was incorrect and has been corrected.
=> doc: fix `ttp-visualize-sigma` description

README-Japanese.md, README.md
=> fix: timeline-tasks option description

src/takajopkg/general.nim, src/takajopkg/htmlReport.nim, src/takajopkg/splitJsonTimeline.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackComputers.nim, src/takajopkg/stackIpAddresses.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackUsers.nim, src/takajopkg/sysmonProcessTree.nim, src/takajopkg/timelineLogon.nim, src/takajopkg/timelineSuspiciousProcesses.nim, src/takajopkg/ttpVisualizeSigma.nim, src/takajopkg/vtDomainLookup.nim, src/takajopkg/vtHashLookup.nim, src/takajopkg/vtIpLookup.nim, src/takajopkg/web/htmlServer.nim
- Closed #227
https://github.com/Yamato-Security/takajo/actions/runs/13327584995
https://github.com/Yamato-Security/takajo/actions/runs/13327589698
=> fix: compiler warning in Nim 2.2.2

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, takajo.nimble
Finalize 2.8.0 for the Ninja Day release
=> finalize 2.8.0

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/timelineLogon.nim
- Closed #233 
- https://github.com/Yamato-Security/hayabusa-rules/blob/b614050bd375f38bff3af3027692fafe520108f3/hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_302_Info_LogonSuccess.yml
- https://github.com/Yamato-Security/hayabusa-rules/blob/b614050bd375f38bff3af3027692fafe520108f3/hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_303_Info_Logoff.yml
https://github.com/Yamato-Security/takajo/actions/runs/14095754254
=> feat: add RDS Gateway Logon event to timeline-logon

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/automagic.nim, src/takajopkg/metricsUsers.nim
- Closed #237 
https://github.com/Yamato-Security/takajo/actions/runs/14154834292
=> feat: add metrics-users command

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/general.nim, takajo.nimble
- Closed #240 
- https://github.com/Yamato-Security/takajo/actions/runs/14353636595
- https://github.com/Yamato-Security/takajo/actions/runs/14353626754
=> fix: takajo current dir check

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/metricsComputers.nim
- Closed #243 
- https://github.com/Yamato-Security/takajo/actions/runs/14416093696
=> feat: improve metrics-computer uptime

CHANGELOG-Japanese.md, CHANGELOG.md, mitre-attack.json, src/takajo.nim, src/takajopkg/ttpResult.nim, takajo.nimble
Since version 17 of MITER ATT&CK has been released, I have updated the mitre-attack.json.
- https://attack.mitre.org/resources/updates/updates-april-2025/
- https://medium.com/mitre-attack/attack-v17-dfb59eae2204
- OS: macOS Sequoia version 15.4.1
- Hayabusa v3.3.0-dev
- https://github.com/Yamato-Security/takajo/actions/runs/14603369158
=> feat: update to MITRE ATT&CK v17

.github/workflows/release.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/listHashes.nim, src/takajopkg/timelineLogon.nim, takajo.nimble
- Closed #250
- https://github.com/Yamato-Security/takajo/actions/runs/15086634680
=> fix: add newline in automagic table

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim
Finalizing 2.10.0 for release. @fukusuket Please check.
=> finalize 2.10.0

.github/workflows/integration-test.yml, .github/workflows/release.yml
- #253 
https://github.com/Yamato-Security/takajo/actions/runs/15219659110
=> fix: release automation action

CHANGELOG-Japanese.md, CHANGELOG.md, templates/common.js, templates/static/computer_summary.htm, templates/static/content.htm, templates/static/index.htm
fix: #204 Add commas and percentages to numbers
=> fix #204 Add commas and percentages to numbers
