Yamato-Security/takajo

src/takajo.nim, src/takajopkg/submodule.nim, tests/testsubmodule.nim
- added proc getYMLLists 
- added test
```
>nimble test
Verifying dependencies for takajo@0.1.0
Info: Dependency on docopt@>= 0.6 already satisfied
Verifying dependencies for docopt@0.6.8
Info: Dependency on regex@>= 0.7.4 already satisfied
Verifying dependencies for regex@0.19.0
Info: Dependency on unicodedb@>= 0.7.2 already satisfied
Verifying dependencies for unicodedb@0.10.0
Compiling C:\Users\nexts\opensource\hayabusa-tools\tests\testsubmodule (from package takajo) using c backend
[OK] csv file path import
[OK] check getYMLLists
Success: Execution finished
Success: All tests passed
```
=> Check yml files list in target folder

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/submodule.nim
- Added Display logo
``` bash
>./takajo.exe
╔════════╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗║║╚═╝╠╗║║║ ║║
Usage:
takajo {SUBCMD}  [sub-command options & parameters]
where {SUBCMD} is one of:
help                        print comprehensive or per-cmd help
list-undetected-evtx-files  List up undetected evtx files.
list-unused-rules           List up unused rules.
takajo {-h|--help} or with no args at all prints this message.
takajo --help-syntax gives general cligen syntax help.
Run "takajo {help SUBCMD|SUBCMD --help}" to see help for just SUBCMD.
Run "takajo help" to get *comprehensive* help.
Top-level --version also available
```
- --quiet option 
```
> ./takajo.exe …
```
=> Added display logo

.gitignore, CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajo.nim, takajo.nimble
- added output option (`-o, --output`)
- feature of output result to text file 
- readme update
- changelog update
- changed version num (0.0.1 -> 1.0.0-dev)
- [evtx.txt](https://github.com/Yamato-Security/takajo/files/9741344/evtx.txt)
<details>
<summary>
./takajo.exe undetected-evtx -t .\takajo2.csv -e ..\hayabusa-sample-evtx\ -o evtx.txt
</summary>
```
> ./takajo.exe undetected-evtx -t .\takajo2.csv -e ..\hayabusa-sample-evtx\ -o evtx.txt
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
Finished. 
---------------
Undetected evtx file identified.
17.41% of the evtx files did not have any detections.
Number of evtx files not detected: 101
Saved File evtx.txt
``` …
=> added output feature

src/takajo.nim, src/takajopkg/splitJsonTimeline.nim
Added split-json-timeline command.
- OS: macOS montery version 13.4
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
- Nim Compiler Version 1.6.12[macOS: arm64] 
`help/version` option works.
```
fukusuke@fukusukenoAir hayabusa-2.6.0-all-platforms % ./takajo split-json-timeline -h
Usage:
split-json-timeline [REQUIRED,optional-params]
split up a large JSONL timeline into smaller ones based on the computer name (input: JSONL, profile: any)
Options:
-h, --help                           print this cligen-erated help
--help-syntax                        advanced: prepend,plurals,..
--version          bool    false     print version
-o=, --outputDir=  string  "output"  output directory (default: output)
-q, --quiet        bool    false     do not display the launch banner
-t=, --timeline= …
```
=> feat: add `split-json-timeline` command

CHANGELOG-Japanese.md, CHANGELOG.md, takajo.nimble
- Fixed #31
- Explicitly specify the installed version of `suru` as the latest commit [f6f1e607c585b2bc2f71309996643f0555ff6349](https://github.com/de-odex/suru/commit/f6f1e607c585b2bc2f71309996643f0555ff6349)
- because [this code](https://github.com/de-odex/suru/blob/e99984f309013bb4c0cdc32c59bcadea9d82b948/src/suru.nim#L241)  causes compilation error
- OS: macOS montery version 13.1
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
Compile succeed as follows.
```
fukusuke@fukusukenoAir takajo % nimble build -d:release -d:ssl
Verifying dependencies for takajo@2.0.0
Installing cligen@>= 1.5
Downloading https://github.com/c-blake/cligen.git using git
Verifying dependencies for cligen@1.6.13
Installing cligen@1.6.13
Success:  cligen installed successfully.
Installing …
```
=> fix: suru compile error with Nim 2.0.0

.github/workflows/nim.yml, CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/takajo.nim, src/takajopkg/general.nim, src/takajopkg/vtDomainLookup.nim, src/takajopkg/vtHashLookup.nim, src/takajopkg/vtIpLookup.nim
- Feat  #30
- Make VirusTotal API lookup multithreaded
- Start a thread for each VirusTotal API query request  
- Using a thread from the thread pool with [spawn](https://nim-by-example.github.io/parallelism/)
- API query results executed in multithread are stored in [Channel](https://nim-by-example.github.io/channels/)
- The reason I used a Channel is so that we can receive the results thread-safely.
- [In Nim, Channel cannot be a proc argument, so define it in the global scope](https://nim-lang.org/docs/manual_experimental.html#parallel-amp-spawn-spawn-statement) 
I have confirmed the following behavior: https://github.com/Yamato-Security/takajo/pull/34#issuecomment-1703971022
However, I'm sorry, since my API is a free version :( I haven't checked to see if it's faster... If possible, I …
=> feat: make vt lookup multithreaded

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/timelineSuspiciousProcesses.nim
- Fixed  #35
- If conversion fails with `fromHex`, consider it as a decimal number
- OS: macOS montery version 13.4.1
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
```
% nim -v
% nimble -v
```
`timeline-suspicious-process` command success.
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.8.0-all-platforms % ./takajo timeline-suspicious-processes -t result.jsonl -o out.txt
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
Started the Timeline Suspicious Processes command
This command will a CSV timeline of suspicious processes.
The default minimum level of alerts is high.
You can …
```
=> fix: `timeline-suspicious-process` command `Error: unhandled exception: invalid hex integer: [ValueError]`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/vtDomainLookup.nim, src/takajopkg/vtHashLookup.nim, src/takajopkg/vtIpLookup.nim
- Fixed  #39
- OS: macOS montery version 13.4.1
```
% nim -v
% nimble -v
```
`vt-domain-lookup` command with invalid api key does not fail as follows.
```
./takajo-new vt-domain-lookup -a invalidkey --domainList domain.txt -o out.csv
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
Started the VirusTotal Domain Lookup command
This command will lookup a list of domains on VirusTotal.
Specify -j results.json to save the original JSON responses.
The default rate is 4 requests per minute so increase this if you have a premium membership.
Loading domains. Please wait.
Loaded domains: 2 …
```
=> fix: `JsonParsingError` when `vt-lookup` failed with invalid api key

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/timelineSuspiciousProcesses.nim
- Fixed #49 
- Changed key `ParentGUID` to `ParentPGUID`
- Apply `PID` hex conversion process only if `PID` is not decimal
- related https://github.com/Yamato-Security/hayabusa/pull/1154
```
% nim -v
% nimble -v
```
```
% ./takajo timeline-suspicious-processes -t timeline.jsonl -o result.csv
```
**Event ID 4688 Security**
PID `1216` and `1404` are output. 
4688 does not have ParentPGUID, so it is not output.
```
% cat result.csv | head -n 5
Timestamp,Computer,Type,Level,Rule,RuleAuthor,Cmdline,Process,PID,User,LID,LGUID,ProcessGUID,ParentCmdline,ParentPID,ParentPGUID,Description,Product,Company,MD5 Hash,SHA1 Hash,SHA256 Hash,Import Hash
2016-08-19 04:59:33.255 …
```
=> fix: Fixed key to `ParentPGUID`. Apply `PID` hex conversion process only if `PID` is not decimal

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/sysmonProcessTree.nim, takajo.nimble
- Fixed #51
- Remove duplicates `processObject` when moving `processObject` to children 
```
% nim -v
% nimble -v
```
Duplicate processes are not displayed in the steps to reproduce #51
```
% ./takajo sysmon-process-tree -t sample.jsonl -p 747F3D96-B7A5-5EA4-0000-0010EAB91300
...
C:\Windows\System32\smss.exe (2020-04-26 07:19:20.134 +09:00 / 300 / 747F3D96-B75F-5EA4-0000-0010622C0000 / 747F3D96-B75F-5EA4-0000-0010EB030000)
└ C:\Windows\System32\smss.exe (2020-04-26 07:19:22.596 +09:00 / 388 / 747F3D96-B763-5EA4-0000-00106A480000 / 747F3D96-B75F-5EA4-0000-0010622C0000)
└ C:\Windows\System32\wininit.exe (2020-04-26 07:19:23.222 +09:00 / 468 / …
```
=> fix duplicate process output `sysmon-process-tree`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/sysmonProcessTree.nim
- Fixed #53
- Added [Process GUID format](https://learn.microsoft.com/en-us/windows/win32/msi/guid) check for invalid input(`-p` option)
- Added a check to see if the specified `Process GUID`(with `-p`) exists in `stockedProcessObjectTable`
- Not present in s`tockedProcessObjectTable` equals not present in JSONL
```
% nim -v
% nimble -v
```
If a `Process GUID` in the wrong format is specified with `-p`, the following message will be output:
```
% ./takajo sysmon-process-tree -t timeline.jsonl -p invalid -q
The format of the Process GUID specified with the -p option is invalid. Please specify a valid Process GUID.
```
If a `Process GUID` not exists in JSONL is specified …
=> fix: not output an exception when a `PGUID` that does not exist in JSONL

src/takajopkg/general.nim, src/takajopkg/splitCsvTimeline.nim
- fixed #58
- Hayabusa v2.10.0-dev
- Nim: 2.0.0
I performed [the reproduction steps](https://github.com/Yamato-Security/takajo/issues/58#issue-1955748988) and confirmed that the issue was fixed as shown below.
```
% ./takajo list-domains -t timeline-ps.jsonl -o domains.txt -q
Started the List Domains command
Local queries to workstations are filtered out by default, but can be included with -w, --includeWorkstations.
Sub-domains are also filtered out by default, but can be included with -s, --includeSubdomains.
Domains ending with .lan, .LAN or .local are filtered out.
Total lines: 149
Extracting domain queries from Sysmon 22 events. Please wait.
100%|█████████████████████████| 149/149 [ 0.0s< 0.0s,  44.60k/sec]
Domains: 0 …
```
=> fix: increment count for last line without `\n`

src/takajopkg/timelineSuspiciousProcesses.nim
Fixed typo in `timeline-suspicious-process` command console message.
- https://github.com/Yamato-Security/takajo/issues/35#issuecomment-1777201074
-  `This command will ...(word missing here) a CSV timeline of suspicious processes`
- Hayabusa v2.10.0-dev
- Nim: 2.0.0
Folloing typo message fixed as follows.
`This command will a CSV timeline of suspicious processes.`
↓
`This command will create a CSV timeline of suspicious processes.`
```
% ./takajo timeline-suspicious-processes -t timeline-ps.jsonl -q
Started the Timeline Suspicious Processes command
This command will create a CSV timeline of suspicious processes.
The default minimum level of alerts is high.
You can change the minimum level with -l, --level=.
Total lines: …
```
=> fix typo in `timeline-suspicious-process` command console message

src/takajopkg/general.nim
- fixed #63 
- Hayabusa v2.10.0
- Nim: 2.2.0-dev
% ./takajo list-undetected-evtx -t out.jsonl -e ../hayabusa-sample-evtx
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
Failed to open 'out.jsonl' because it is not in CSV format.
Please specify a CSV that has been created with the Hayabusa csv-timeline command.
% ./takajo list-unused-rules -t out.jsonl -r ./rules
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
Failed to open 'out.jsonl' because it is not in CSV format.
Please specify a CSV that has been created with …
=> fix: add handling for CSV parse exception

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/extractScriptblocks.nim, src/takajopkg/general.nim, src/takajopkg/timelinePartitionDiagnostic.nim
- feat: #67
-  extract `EventID` == `1006` and `Channel` == `MS-Win-Partition/Diagnostic`
- output following field
- `Timestamp`
- `Computer`
- `Manufacturer` 
- `Model`
- `Revision` 
- `SerialNumber`
- related: https://github.com/Yamato-Security/hayabusa-rules/pull/534
- Hayabusa v2.10.1
- Nim: 2.0.0
without -o option
with -o option
I would appreciate it if you could review when you have time🙏
=> feat: add timeline-partition-diagnostic command

src/takajopkg/extractScriptblocks.nim, src/takajopkg/general.nim, src/takajopkg/timelinePartitionDiagnostic.nim
- fixed: #74 
- OS: Windows11
- Hayabusa v2.11.0
- Nim: 2.0.0
I would appreciate it if you could review when you have time🙏
=> fix: modify mojibake in stdout `timeline-partition-diagnostic`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/ttpVisualize.nim
- related: #76
- added `RuleTile` to comment field.
- It would be better for the user to be able to check on ATT&CK Navigator **which rule the techniqueID was detected by**.
example:
```json
{
"name": "Hayabusa detection result heatmap",
"versions": {
"attack": "14",
"navigator": "4.9.1",
"layer": "4.5"
},
"domain": "enterprise-attack",
"description": "Hayabusa detection result heatmap",
"techniques": [
{
"color": "#fd8d3c",
"techniqueID": "T1070.006",
"comment": "Unauthorized System Time Modification"
},
{
"color": "#fd8d3c",
"techniqueID": "T1098",
"comment": "A Member Was Added to a Security-Enabled Global Group"
}
]
}
```
- Nim: 2.0.0
```
./takajo ttp-visualize -t timeline.jsonl
...
Started the TTP Visualize command.
This command …
```
=> feat: add `RuleTitle` to`mitre-attack-navigator.json`

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/ttpSummary.nim
- related: #78 
- added `RuleTitle` to `ttp-summary` command output
- Nim: 2.0.0
```csv
Computer,Tactic,Technique,Sub-Technique,RuleTitle,Count
-,08. Credential Access,Brute Force,Password Spraying,PW Guessing,1
DESKTOP-JR78RLP,07. Defense Evasion,Impair Defenses,Disable Windows Event Logging,"PW Spray, Event Log Service Startup Type Changed To Disabled",3
DESKTOP-JR78RLP,07. Defense Evasion,Indicator Removal,Clear Windows Event Logs,Important Log File Cleared,1
DESKTOP-M5SN04R,10. Lateral Movement,Remote Services,SMB/Windows Admin Shares,"Log Cleared, Metasploit SMB Authentication",2
IE10Win7,04. Execution,System Services,Service Execution,"Rundll32 Execution Without Parameters, Metasploit SMB Authentication",3561
IE10Win7,05. …
```
=> feat: add `RuleTitle` to `ttp-summary` command output

src/takajo.nim, src/takajopkg/ttpVisualize.nim
- feat: #90 
I use the following four red colors.
The color-coding logic is simply divided into four categories based on score( = number of detections).
```Nim
if score == 1:
result.color = "#fca2a2"
elif score == 2 :
result.color = "#fc6b6b"
elif score == 3 :
result.color = "#fc3b3b"
else:
result.color = "#e60d0d"
```
=> feat: add color gradient to ttp-visualize

.github/workflows/release.yml
- Fixed: #89  
https://github.com/Yamato-Security/takajo/actions/runs/7852542825
Unfortunately...Since it is no longer possible to upload multiple jobs to a single artifact using the upload-artifact action, artifacts are separated by OS.
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
=> chg: update GitHub Actions libraries

.github/workflows/integration-test.yml
- Related: #99 
-  Added integration tests to make sure we haven't broken any commands before refactoring.
I have confirmed that the repository in my account works correctly as shown below.
https://github.com/fukusuket/takajo-fukusuket/actions/runs/7860706970/job/21448190160
Also, while creating the test, I found a bug in the `split-csv-timeline` command as follows, so I will create an issue.
https://github.com/fukusuket/takajo-fukusuket/actions/runs/7860549962/job/21447839645
=> test: add integration-test for takajo command

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/splitCsvTimeline.nim
- Closed: #103
- Hayabusa v2.12.0/v2.13.0
- Nim: 2.0.2
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.12.0-mac % ./takajo split-csv-timeline -t timeline.csv -q
Started the Split CSV Timeline command
This command will split a large CSV timeline into many multiple ones based on computer name.
If you want to separate the field data by newlines, add the -m option.
Total lines: 32373
Splitting the Hayabusa CSV timeline. Please wait.
100%|█████████████████████████| 32373/32373 [ 0.3s< 0.0s, 192.24k/sec]
Saved file: output/37L4247D28-05-HayabusaResults.csv (33.40 KB)
Saved file: output/IE8Win7-HayabusaResults.csv (82.02 KB)
Saved file: output/IE9Win7-HayabusaResults.csv (9.91 KB)
Saved file: …
```
=> fix: calculate computer column number each execution

.github/workflows/integration-test.yml, src/takajo.nim, src/takajopkg/extractScriptblocks.nim, src/takajopkg/general.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackDNS.nim, src/takajopkg/stackLogons.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackServices.nim, src/takajopkg/stackTasks.nim, src/takajopkg/stackUtil.nim, src/takajopkg/takajoTerminal.nim
- Closed: #112
- Related: #99
- Refactor: I made the duplicated stack command logic into a function and deleted it.
- Test: added integration-test case 
- Output Count, level, RuleTitle in table layout
- Sort by level(cirt -> high -> med -> low)
- If the number of alerts is the same, sort in alphabetical order
I tried creating it with the above specifications, but what do you think? Please let me know if there is anything that should be changed :)
In the integration test below, I confirmed that the altert level is output to stdout.
- https://github.com/Yamato-Security/takajo/actions/runs/7942064926/job/21684997377
=> feat: show alert level for stacking command

src/takajo.nim
Just updated the takajo version and name for release
=> finalize 2.4.0

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackComputers.nim, src/takajopkg/stackDNS.nim, src/takajopkg/stackIpAddresses.nim, src/takajopkg/stackIpaddresses.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackServices.nim, src/takajopkg/stackTasks.nim, src/takajopkg/stackUsers.nim, src/takajopkg/stackUtil.nim
- Closed: #130 
- Closed: #129 
- Related: #99 
- The JSONL For loop in the stack command is almost the same, so move the duplicate code to stackUtil `processJSONL` 
- Added integration-test case
- Nim: 2.0.2
In the integration test below, I confirmed that the all commands succeeded.
- https://github.com/Yamato-Security/takajo/actions/runs/8126728721
=> feat: stack-users/stack-ip-addresses

.github/workflows/integration-test.yml, src/takajo.nim, src/takajopkg/automagic.nim, src/takajopkg/extractScriptblocks.nim, src/takajopkg/general.nim, src/takajopkg/listDomains.nim, src/takajopkg/listHashes.nim, src/takajopkg/listIpAddresses.nim, src/takajopkg/stackCmdlines.nim, src/takajopkg/stackCommon.nim, src/takajopkg/stackComputers.nim, src/takajopkg/stackDNS.nim, src/takajopkg/stackIpAddresses.nim, src/takajopkg/stackLogons.nim, src/takajopkg/stackProcesses.nim, src/takajopkg/stackServices.nim, src/takajopkg/stackTasks.nim, src/takajopkg/stackUsers.nim, src/takajopkg/stackUtil.nim, src/takajopkg/takajoCore.nim, src/takajopkg/timelineLogon.nim, src/takajopkg/timelinePartitionDiagnostic.nim, src/takajopkg/timelineSuspiciousProcesses.nim, src/takajopkg/timelineTasks.nim, src/takajopkg/ttpSummary.nim, src/takajopkg/ttpVisualize.nim
- Closed #121 
- Applies only to commands that take JSONL as input 
- Related: #99 
- Related: #132
- Apply [Template method pattern](https://refactoring.guru/design-patterns/template-method) for `automagic` command
- Refactoring to reuse logic in `automagic` as below 
- [src/takajopkg/automagic.nim](https://github.com/Yamato-Security/takajo/blob/refactor-for-automagic-command/src/takajopkg/automagic.nim)
- The `automagic` command is commented out in this PR. I will create another PR for `automagic`.  
- The common behavior for all commands that take JSONL as input is defined below
-  [src/takajopkg/takajoCore.nim](https://github.com/Yamato-Security/takajo/blob/refactor-for-automagic-command/src/takajopkg/takajoCore.nim) 
-  For processing specific to each command, extend `AbstractCmd` …
=> refactor: apply Template method pattern for automagic command

src/takajopkg/hayabusaJson.nim, src/takajopkg/ttpResult.nim, src/takajopkg/ttpVisualize.nim, src/takajopkg/ttpVisualizeSigma.nim
- Closed: #136 
- Nim: 2.0.2
I confirmed that there is no difference between the execution results of the ttp-visualize command in 2.4.0 and the following.
```
% ./takajo ttp-visualize -t timeline.jsonl
% diff mitre-ttp-heatmap.json mitre-attack-navigator.json
%
```
In the integration test below, I confirmed that the all commands succeeded.
- https://github.com/Yamato-Security/takajo/actions/runs/8298558745
=> fix: ttp-visualize/ttp-summary command does not extract count related rule

src/takajopkg/ttpResult.nim, src/takajopkg/ttpSummary.nim
- Closed: #143 
- Hayabusa v2.14.0-dev
- Nim: 2.0.2
I confirmed that it does not crash as follows.
```
% ./hayabusa json-timeline -d ../hayabusa-sample-evtx -o timeline-standard.jsonl -L -w
% ./takajo automagic -t timeline-standard.jsonl -q
Started the automagic command
Automatically executes as many commands as possible and output results to a new folder.
File: timeline-standard.jsonl (31.97 MB)
Total lines: 32,363
Scanning the Hayabusa timeline. Please wait.
100%|█████████████████████████| 32363/32363 [ 0.6s< 0.0s,  83.13k/sec]
┌───────────────────────────────┬──────────────────────────────────────────────────────┬──────────────────────────────────────────────────────┐
│ Command                       │ …
```
=> fix: automagic crash when not verbose profile jsonl

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/automagic.nim, src/takajopkg/stackLogons.nim
- Closed: #152 
- OS: macOS Sonoma version 14.4.1
- Hayabusa v2.15.0-dev
- Nim: 2.0.2
https://github.com/Yamato-Security/takajo/actions/runs/8690500610/job/23830582091
```
% ./takajo stack-logons -h
Usage:
stack-logons [REQUIRED,optional-params]
stack logons by target user, target computer, source IP address and source computer
Options:
-h, --help                                   print this cligen-erated help
--help-syntax                                advanced: prepend,plurals,..
--version                  bool    false     print version
-l, --localSrcIpAddresses  bool    false     include results when the source IP address is local
-f, --failedLogons         bool    false     stack failed logons instead of successful logons
-s, --skipProgressBar      bool    false …
```
=> feat: added `failedLogons` option `stack-logons`

CHANGELOG-Japanese.md, CHANGELOG.md, mitre-attack.json
Since version 15 of MITER ATT&CK has been released, I have updated the mitre-attack.json.
- https://attack.mitre.org/docs/changelogs/v14.1-v15.0/changelog-detailed.html
- https://medium.com/mitre-attack/attack-v15-26685f300acc
- OS: macOS Sonoma version 14.4.1
- Hayabusa v2.15.0
- Nim: 2.0.2
https://github.com/Yamato-Security/takajo/actions/runs/8835001463
I confirmed that there is no difference in the automagic command results.
```
fukusuke@fukusukenoAir takajo-2.5.0-mac-arm % ./takajo automagic -t timeline.jsonl -o case-1  #with old json
fukusuke@fukusukenoAir takajo-2.5.0-mac-arm % ./takajo automagic -t timeline.jsonl -o case-2  #with new json
fukusuke@fukusukenoAir takajo-2.5.0-mac-arm % diff case-1/TTPSummary.csv case-2/TTPSummary.csv
fukusuke@fukusukenoAir …
```
=> feat: update to MITRE ATT&CK v15.0

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/stackCommon.nim, takajo.nimble
- Closed #162 
- I could not find any changes from the release notes for Nim `2.0.6` regarding specification changes, but the compilation now passes by specifying the CounTable type.
- OS: macOS Sonoma version 14.5
- Hayabusa v2.17.0-dev
Integration-Test/Release automation succeeded as follows.
- https://github.com/Yamato-Security/takajo/actions/runs/9695155689
- https://github.com/Yamato-Security/takajo/actions/runs/9695128439
=> fix: define CountTable type explicitly

.github/workflows/integration-test.yml, .github/workflows/nim.yml, .github/workflows/release.yml
Version 2 of setup-nim-actions has been released, so I updated it.
https://github.com/jiro4989/setup-nim-action?tab=readme-ov-file#v2-version-was-released-tada
- https://github.com/Yamato-Security/takajo/actions/runs/10730617246
- https://github.com/Yamato-Security/takajo/actions/runs/10730557733
=> Update GitHub Actions setup-nim-action@v2

.github/workflows/release.yml
Related: #184 
- Added coping template folder step
- Added the ability to specify the tag name and branch name to build Takajo  
Add parameter to allow branch/tag names to be specified as follows.
- `release_ver`: Version number to use for file names
- `branch_or_tag`: Branch or tag name to build takajo
Actions succeeded as follows
https://github.com/Yamato-Security/takajo/actions/runs/10759326195
The zip could be downloaded as follows
=> fix: Release Automation GitHub Actions add copy templates folder

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajo.nim, src/takajopkg/extractCredentials.nim, src/takajopkg/takajoCore.nim
- Closed #188 
- Extract the password from the following command line
- wmic
- schtasks
- net user
- psexec
```
% ./takajo
┏━━━━┳━━━┳┓┏━┳━━━┓ ┏┳━━━┓
┃┏┓┏┓┃┏━┓┃┃┃┏┫┏━┓┃ ┃┃┏━┓┃
┗┛┃┃┗┫┃ ┃┃┗┛┛┃┃ ┃┃ ┃┃┃ ┃┃
┃┃ ┃┗━┛┃┏┓┓┃┗━┛┣┓┃┃┃ ┃┃
┃┃ ┃┏━┓┃┃┃┗┫┏━┓┃┗┛┃┗━┛┃
┗┛ ┗┛ ┗┻┛┗━┻┛ ┗┻━━┻━━━┛
Version: 2.7.0 Dev Build
Usage: takajo.exe <COMMAND>
Commands:
help                           print comprehensive or per-cmd help
automagic                      automatically executes as many commands as possible and output results to a new folder
extract-credentials            extract credentials from the timeline
...
Examples:
automagic -t ../hayabusa/timeline.jsonl [--level low] [--displayTable] -o case-1
extract-credentials -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o credentials.csv …
```
=> feat: add `extract-credentials` command

.github/workflows/integration-test.yml
Update the Hayabusa package name in GitHub Actions
https://github.com/Yamato-Security/takajo/actions/runs/11536148482
=> fix: rename GitHub action's package name

.github/workflows/release.yml
- Closed #213 
https://github.com/Yamato-Security/takajo/actions/runs/11751351964
=> fix: win release zip folder level

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/timelineLogon.nim
- Closed #209 
- Added Rules to Timeline
-  https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_21_Info_RDP-Logon.yml
- https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_23_Info_RDP-Logoff.yml
- SessionID is used to link Logon and Logoff events
https://github.com/Yamato-Security/takajo/actions/runs/11984876447
https://github.com/Yamato-Security/takajo/actions/runs/11984887843
=> feat: add RDP Logon/Logoff to `timeline-logon`

CHANGELOG-Japanese.md, CHANGELOG.md, mitre-attack.json
Since version 16.1 of MITER ATT&CK has been released, I have updated the mitre-attack.json.
- https://attack.mitre.org/resources/updates/updates-october-2024/
- OS: macOS Sequoia version 15.1.1
- Hayabusa v3.0.0-dev
https://github.com/Yamato-Security/takajo/actions/runs/12169888648
=> feat: update to MITRE ATT&CK v16.1 

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/splitCsvTimeline.nim
- Closed #211
https://github.com/Yamato-Security/takajo/actions/runs/12844375962
(Integration-Test in the Linux environment is broken from before this PR and will be fixed)
=> fix: `split-csv-timeine` correlation result

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/web/htmlServer.nim
#232 fix html-server requires you to reparse JSONL file each run.
If the file already exists, the following message is displayed.
```html-report.sqlite already exists. It looks like you have already processed the JSONL file. Do you want to use this file (Y/n): ```
If Y: use html-report.sqlite
If n: overwrite html-report.sqlite
=> fix: html-server requires you to reparse JSONL file each run

.github/workflows/release.yml
copy common.js to templates/static/js
I checked html-server works with following release binary.
https://github.com/Yamato-Security/takajo/actions/runs/15175755537
=> fix: copy common.js to templates/static/js 

CHANGELOG-Japanese.md, CHANGELOG.md, src/takajopkg/vtIpLookup.nim
- Closed #259 
```
% ./takajo vt-ip-lookup -a <api-key> --ipList ipAddresses.txt -o results.csv
```
```
% cat results.csv
Response,IP-Address,SSL-CommonName,SSL-IssuerCountry,LastAnalysisDate,LastModifiedDate,LastHTTPSCertDate,LastWhoisDate,MaliciousCount,HarmlessCount,SuspiciousCount,UndetectedCount,CommunityVotesHarmless,CommunityVotesMalicious,Reputation,RegionalInternetRegistry,Network,Country,AS-Owner,SSL-ValidAfter,SSL-ValidUntil,SSL-Issuer,WhoisInfo,Link,
200,192.168.0.1,Unknown,Unknown,2025-06-30 08:13:08,2025-06-30 10:57:55,Unknown,2022-11-14 16:54:10,0,62,0,32,43,17,-9,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,"NetRange: 192.168.0.0 - 192.168.255.255
CIDR: 192.168.0.0/16
NetName: PRIVATE-ADDRESS-CBLK-RFC1918-IANA-RESERVED
NetHandle: NET-192-168-0-0-1
Parent: NET192 …
```
=> fix: vt-ip-lookup result vt link
